/**
 * A package containing persistant entities that get generated by the ORM
 * <br>
 * <b><u>
 * Note: This package is still under development and the bot itself still uses the {@link com.jagrosh.vortex.database}
 * package for most database connections
 * </u></b>
 */
package com.jagrosh.vortex.hibernate.entities;